name: Workflow testing

on: 
   push:
    branches: [ "main" ]
   pull_request:
    branches: [ "main" ]
   issues:
    types: [opened, edited]
    
jobs:
  here_I_write_my_own_titile:
   env:
            MY_ENV: "John Doe"
   runs-on: ubuntu-latest
   steps:
      - name: Greet the User by me
        run: echo "Hello World!"
      - name: Show directory before checkout
        run: ls -l
      - name: Checkout our code
        uses: actions/checkout@v3
      - name: Show directory after checkout
        run: ls -l
      - name: Show env vars
        run: |
          echo "Hello $MY_ENV"
          echo "Hello $GITHUB_ACTOR"
    
