name: Workflow testing

on: 
   push:
    branches: [ "main" ]
   pull_request:
    branches: [ "main" ]
    
jobs:
  here_I_write_my_own_titile:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the User by me
        run: echo "Hello World!"
    
